"""Warehouse layout builder for pyWarehouse."""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple, Union

import pandas as pd

from .graph import add_undirected_edge, graph_to_edges_df, rectilinear_distance, snap_value, unique_points, wire_line
from .models import Depot, Graph, Point, Product

ProductAddress = Union[Tuple[int, int, int], Tuple[str, int, int, int], Dict[str, Any]]


def make_cross_y_coords(
    slots_per_block: int,
    num_blocks: int,
    slot_pitch: float = 1.0,
    front_corridor: float = 0.0,
    cross_corridor: float = 0.0,
    back_corridor: float = 0.0,
) -> List[float]:
    """Return all horizontal corridor/cross-aisle y coordinates.

    A centerline model is used. ``y=0`` is the front corridor. For every block,
    the block upper boundary is added. Between blocks, a vertical gap equal to
    ``cross_corridor`` is inserted and the lower boundary of the next block is
    added. After the last block, an optional back corridor y-line is added.

    Example with 2 blocks, 20 slots, cross_corridor=3, back_corridor=2:
    ``[0, 20, 23, 43, 45]``.

    ``front_corridor`` is retained in metadata and is most naturally represented
    by putting the start/finish at ``y=-front_corridor`` when the depot is in
    front of the warehouse.
    """
    if slots_per_block <= 0:
        raise ValueError("slots_per_block must be positive")
    if num_blocks <= 0:
        raise ValueError("num_blocks must be positive")
    ys = [0.0]
    lower = 0.0
    for b in range(num_blocks):
        upper = lower + slots_per_block * slot_pitch
        ys.append(float(upper))
        if b < num_blocks - 1:
            lower = upper + cross_corridor
            ys.append(float(lower))
        else:
            if back_corridor > 0:
                ys.append(float(upper + back_corridor))
    return sorted(set(round(y, 10) for y in ys))


@dataclass
class WarehouseLayout:
    """Graph-based warehouse layout with parallel aisles and block cross-corridors."""

    num_aisles: int
    slots_per_block: int
    num_blocks: int = 1
    aisle_spacing: float = 2.0
    slot_pitch: float = 1.0
    front_corridor: float = 0.0
    cross_corridor: float = 0.0
    back_corridor: float = 0.0
    products: Dict[str, Product] = field(default_factory=dict)
    starts: Dict[str, Depot] = field(default_factory=dict)
    finishes: Dict[str, Depot] = field(default_factory=dict)
    metadata: Dict[str, Any] = field(default_factory=dict)

    @classmethod
    def rectangular(
        cls,
        num_aisles: int,
        slots_per_block: int,
        num_blocks: int = 1,
        aisle_spacing: float = 2.0,
        slot_pitch: float = 1.0,
        front_corridor: float = 0.0,
        cross_corridor: float = 0.0,
        back_corridor: float = 0.0,
    ) -> "WarehouseLayout":
        """Create a rectangular/multi-block layout."""
        return cls(
            num_aisles=num_aisles,
            slots_per_block=slots_per_block,
            num_blocks=num_blocks,
            aisle_spacing=aisle_spacing,
            slot_pitch=slot_pitch,
            front_corridor=front_corridor,
            cross_corridor=cross_corridor,
            back_corridor=back_corridor,
        )

    @property
    def aisle_xs(self) -> List[float]:
        return [float(i * self.aisle_spacing) for i in range(self.num_aisles)]

    @property
    def cross_ys(self) -> List[float]:
        return make_cross_y_coords(
            self.slots_per_block,
            self.num_blocks,
            self.slot_pitch,
            self.front_corridor,
            self.cross_corridor,
            self.back_corridor,
        )

    def _is_external_depot_y(self, y: float, tol: float = 1e-9) -> bool:
        """Return True when a depot y-coordinate lies outside storage/cross aisles.

        Starts/finishes are often placed in a front staging corridor such as
        ``y=-1``.  That line is not one of the warehouse cross aisles
        generated by :attr:`cross_ys`, but it is still a walkable depot
        corridor.  Treating it as merely a vertical stub forces paths to go up
        to the front corridor ``y=0`` before moving sideways.  This helper lets
        :meth:`build_graph` add an explicit external horizontal corridor at the
        depot y-coordinate instead.
        """
        ys = self.cross_ys
        return bool(ys and (float(y) < min(ys) - tol or float(y) > max(ys) + tol))

    def depot_corridor_ys(self, tol: float = 1e-9) -> List[float]:
        """Return external horizontal corridor y-lines required by depots.

        Only start/finish y-coordinates outside the storage/cross-aisle envelope
        are promoted to corridor rows.  Product slots inside the storage area do
        not create artificial cross aisles.
        """
        ys: List[float] = []
        for depot in list(self.starts.values()) + list(self.finishes.values()):
            if self._is_external_depot_y(depot.y, tol=tol):
                y = round(float(depot.y), 10)
                if y not in ys:
                    ys.append(y)
        return sorted(ys)

    def horizontal_corridor_ys(self, tol: float = 1e-9) -> List[float]:
        """Return warehouse cross aisles plus external depot corridor rows."""
        ys = list(self.cross_ys) + self.depot_corridor_ys(tol=tol)
        return sorted(set(round(float(y), 10) for y in ys))

    def block_lower_y(self, block: int) -> float:
        if not 0 <= block < self.num_blocks:
            raise ValueError(f"Invalid block index {block}")
        return self.cross_ys[2 * block]

    def address_to_xy(self, aisle: int, slot: int, block: int) -> Point:
        """Convert (aisle, slot, block) to walkable graph coordinates.

        The public address ``slot`` is interpreted as its warehouse coordinate
        along the aisle. With ``slot_pitch=1.0``, slot 5 is therefore located
        at ``y=5.0``. This makes route distances match the coordinates the
        user supplies in ``add_product((id, aisle, slot, block))``.
        """
        if not 0 <= aisle < self.num_aisles:
            raise ValueError(f"Invalid aisle {aisle}; expected 0..{self.num_aisles - 1}")
        if not 1 <= slot <= self.slots_per_block:
            raise ValueError(f"Invalid slot {slot}; expected 1..{self.slots_per_block}")
        if not 0 <= block < self.num_blocks:
            raise ValueError(f"Invalid block {block}; expected 0..{self.num_blocks - 1}")
        x = self.aisle_xs[aisle]
        y = self.block_lower_y(block) + slot * self.slot_pitch
        return (float(x), float(y))

    def add_product(self, id: str, aisle: int, slot: int, block: int = 0, **metadata: Any) -> "WarehouseLayout":
        x, y = self.address_to_xy(aisle, slot, block)
        self.products[id] = Product(id=id, aisle=aisle, slot=slot, block=block, x=x, y=y, metadata=metadata)
        return self

    def add_products(self, products: Sequence[ProductAddress]) -> "WarehouseLayout":
        """Add many products.

        Accepted formats:
        - (aisle, slot, block) -> automatic IDs P001, P002, ...
        - (id, aisle, slot, block)
        - {"id": "P001", "aisle": 0, "slot": 3, "block": 0}
        """
        auto_idx = len(self.products) + 1
        for record in products:
            if isinstance(record, dict):
                pid = str(record.get("id", f"P{auto_idx:03d}"))
                aisle = int(record["aisle"])
                slot = int(record["slot"])
                block = int(record.get("block", 0))
                metadata = {k: v for k, v in record.items() if k not in {"id", "aisle", "slot", "block"}}
            elif len(record) == 3:  # type: ignore[arg-type]
                pid = f"P{auto_idx:03d}"
                aisle, slot, block = record  # type: ignore[misc]
                metadata = {}
            elif len(record) == 4:  # type: ignore[arg-type]
                pid, aisle, slot, block = record  # type: ignore[misc]
                pid = str(pid)
                metadata = {}
            else:
                raise ValueError("Each product must be (aisle, slot, block), (id, aisle, slot, block), or a dict")
            self.add_product(pid, int(aisle), int(slot), int(block), **metadata)
            auto_idx += 1
        return self

    def add_start(self, id: str = "START", x: float = 0.0, y: float = 0.0, **metadata: Any) -> "WarehouseLayout":
        self.starts[id] = Depot(id=id, x=float(x), y=float(y), kind="start", metadata=metadata)
        return self

    def add_finish(self, id: str = "FINISH", x: float = 0.0, y: float = 0.0, **metadata: Any) -> "WarehouseLayout":
        self.finishes[id] = Depot(id=id, x=float(x), y=float(y), kind="finish", metadata=metadata)
        return self

    def set_start(self, id: str = "START", x: float = 0.0, y: float = 0.0, **metadata: Any) -> "WarehouseLayout":
        self.starts.clear()
        return self.add_start(id, x, y, **metadata)

    def set_finish(self, id: str = "FINISH", x: float = 0.0, y: float = 0.0, **metadata: Any) -> "WarehouseLayout":
        self.finishes.clear()
        return self.add_finish(id, x, y, **metadata)

    def _project_to_corridor(self, p: Point) -> Tuple[Point, Optional[Tuple[Point, Point]]]:
        """Attach an off-corridor point to the nearest aisle or cross-aisle."""
        x, y = p
        xs = self.aisle_xs
        ys = self.cross_ys
        on_x = any(abs(x - ax) <= 1e-9 for ax in xs)
        on_y = any(abs(y - cy) <= 1e-9 for cy in ys)
        if on_x or on_y:
            sx = snap_value(x, xs, 1e-9) if on_x else float(x)
            sy = snap_value(y, ys, 1e-9) if on_y else float(y)
            return (sx, sy), None
        nx = min(xs, key=lambda ax: abs(x - ax)) if xs else x
        ny = min(ys, key=lambda cy: abs(y - cy)) if ys else y
        px = (nx, float(y))
        py = (float(x), ny)
        if abs(x - nx) <= abs(y - ny):
            return px, (p, px)
        return py, (p, py)

    def build_graph(self, include_backbone: bool = True) -> Tuple[Graph, Dict[Point, Dict[str, Any]], pd.DataFrame]:
        """Build the weighted Steiner/corridor graph.

        Returns ``(G, node_attrs, edges_df)``.

        Notes
        -----
        Starts and finishes can be placed outside the warehouse envelope, for
        example in a front staging corridor at ``y=-1``.  When such depots are
        present, the graph now creates an explicit horizontal depot corridor at
        that y-coordinate and links it to every aisle extension.  Therefore a
        route from ``START=(0,-1)`` to ``FINISH=(25,-1)`` can move directly
        along ``y=-1`` instead of being forced up to ``y=0`` and back down.
        """
        aisle_xs = self.aisle_xs
        cross_ys = self.cross_ys
        depot_ys = self.depot_corridor_ys()
        horizontal_ys = sorted(set(cross_ys + depot_ys))

        # Cross-aisle intersections plus external depot-corridor intersections.
        # The latter are the small aisle extensions that make an off-front or
        # off-back staging line walkable.
        corner_nodes: List[Point] = [(x, y) for x in aisle_xs for y in horizontal_ys]
        product_points = [p.point for p in self.products.values()]
        terminal_points: List[Point] = product_points[:]
        stubs: List[Tuple[Point, Point]] = []

        def on_external_depot_corridor(point: Point) -> bool:
            return any(abs(float(point[1]) - y) <= 1e-9 for y in depot_ys)

        def register_depot(point: Point) -> Tuple[Point, Optional[Tuple[Point, Point]]]:
            # A start/finish on an external depot corridor is already on a
            # walkable horizontal line, even when its x-coordinate is not an
            # aisle centerline.  Keep the user-supplied coordinate as the real
            # terminal.
            if on_external_depot_corridor(point):
                y = snap_value(point[1], depot_ys, 1e-9)
                return (float(point[0]), float(y)), None
            return self._project_to_corridor(point)

        start_points: Dict[str, Point] = {}
        finish_points: Dict[str, Point] = {}
        for sid, s in self.starts.items():
            projected, stub = register_depot(s.point)
            start_points[sid] = projected
            terminal_points.append(projected)
            if stub:
                terminal_points.append(stub[0])
                stubs.append(stub)
        for fid, f in self.finishes.items():
            projected, stub = register_depot(f.point)
            finish_points[fid] = projected
            terminal_points.append(projected)
            if stub:
                terminal_points.append(stub[0])
                stubs.append(stub)

        V = unique_points(corner_nodes + terminal_points, tol=1e-9)
        G: Graph = {p: {} for p in V}

        # Vertical aisles and depot extensions: every node lying on an aisle
        # centerline is connected by y order.  If an external depot corridor
        # exists, this creates the short extension from y=-1 to y=0, etc.
        for x in aisle_xs:
            col = sorted([p for p in V if abs(p[0] - x) <= 1e-9], key=lambda q: q[1])
            wire_line(G, col)
        # Horizontal cross aisles and external depot corridors.
        for y in horizontal_ys:
            row = sorted([p for p in V if abs(p[1] - y) <= 1e-9], key=lambda q: q[0])
            wire_line(G, row)
        # Stubs from off-corridor starts/finishes that are not on an external
        # depot corridor.
        for u, v in stubs:
            if u not in G:
                G[u] = {}
            if v not in G:
                G[v] = {}
            add_undirected_edge(G, u, v)

        # node attributes
        node_attrs: Dict[Point, Dict[str, Any]] = {}
        corner_set = set(corner_nodes)
        product_by_point: Dict[Point, List[str]] = {}
        for pid, p in self.products.items():
            product_by_point.setdefault(p.point, []).append(pid)

        start_ids_by_point: Dict[Point, List[str]] = {}
        finish_ids_by_point: Dict[Point, List[str]] = {}
        for sid, p in start_points.items():
            start_ids_by_point.setdefault(p, []).append(sid)
        for fid, p in finish_points.items():
            finish_ids_by_point.setdefault(p, []).append(fid)

        for p in G.keys():
            ids: List[str] = []
            labels: List[str] = []
            kinds: List[str] = []
            if p in product_by_point:
                ids.extend(product_by_point[p])
                labels.append("Pick")
                kinds.append("pick")
            if p in start_ids_by_point:
                ids.extend(start_ids_by_point[p])
                labels.append("Start")
                kinds.append("start")
            if p in finish_ids_by_point:
                ids.extend(finish_ids_by_point[p])
                labels.append("Finish")
                kinds.append("finish")
            if labels:
                label = "/".join(dict.fromkeys(labels))
                node_attrs[p] = {"type": "terminal", "label": label, "id": "/".join(ids), "kinds": kinds}
            elif p in corner_set:
                node_attrs[p] = {"type": "steiner", "label": "Corner", "id": f"C({p[0]:g},{p[1]:g})"}
            else:
                node_attrs[p] = {"type": "aux", "label": "Stub", "id": f"A({p[0]:g},{p[1]:g})"}

        return G, node_attrs, graph_to_edges_df(G)

    def terminal_points(self, kind: Optional[str] = None) -> Dict[str, Point]:
        """Return terminal id -> point for products/starts/finishes."""
        data: Dict[str, Point] = {}
        if kind in (None, "pick", "product"):
            data.update({pid: p.point for pid, p in self.products.items()})
        if kind in (None, "start"):
            data.update({sid: s.point for sid, s in self.starts.items()})
        if kind in (None, "finish"):
            data.update({fid: f.point for fid, f in self.finishes.items()})
        return data
